name: generate arcade contribution graphs

on:
  schedule:
    - cron: '0 0 * * *'   # otomatis update tiap hari jam 00:00 UTC
  workflow_dispatch:        # bisa trigger manual
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: generate pacman & galaga SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'pacman,galaga'

      - name: push SVGs ke branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
